config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  get 'home/about'
  get 'home/lookup'
  post "/home/lookup" => 'home/lookup'
  root 'home#index'

end

app/models/crypto.rb
class Crypto < ActiveRecord::Base
    belongs_to :user
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_crypto = JSON.parse(@response)
    @profit_los = 0
      
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_crypto = JSON.parse(@response)
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end
    def correct_user
      @correct = current_user.cryptos.find_by(id: params[:id])
      redirect_to cryptos_path, notice: "YoU sHalL Not PaSS TO ThiS uSEr!" if @correct.nil?
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @my_coins = ["BTC", "XRP", "ADA", "XLM", "STEEM"]
  end
    
    def about
    end
    
    def lookup
      require 'net/http'
      require 'json'
      @url = 'https://api.coinmarketcap.com/v1/ticker/'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @lookup_coin = JSON.parse(@response)
      
      @symbol = params[:sym]
    
      if @symbol
        @symbol = @symbol.upcase
      end
      
     if @symbol == ""
      @symbol  = "Hey You Forgot To Enter A Currency!"
     end
    
  
    end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_for(@crypto) do |f| %>
  <% if @crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
      <% @crypto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol, class: "form-control" %>
  </div>
  <div class="field">

    <%= f.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>
  <div class="field">
    <%= f.label :cost_per %><br>
    <%= f.text_field :cost_per, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :amount_owned %><br>
    <%= f.text_field :amount_owned, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form' %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<h1>Listing Cryptos</h1>
<br/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Curr Price</th>
      <th>Rank</th>
      <th>1hr%</th>
      <th>7hr%</th>
      <th>7 Day%<th> 
      <th>Curr Acct Value</th>
      <th>Total Paid</th>
      <th>Profit/Lost</th>
      <th>Cost Paid Per</th>
      <th>Amount Owned</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
      <%if crypto.user_id == current_user.id %>
        <% if crypto.symbol %>
          <% crypto.symbol = crypto.symbol.upcase %>
        <%end%>
        <tr>
        <% for x in @lookup_crypto %>
          <% if crypto.symbol == x["symbol"] %>
              <td><%= link_to x["name"], crypto %></td>
              <td>$<%= x["price_usd"] %></td>
              <td><%= x["rank"] %></td>
              <td>$<%= x["per_ch_1hr"] %></td>
              <td>$<%= x["per_ch_24h"] %></td>
              <td>$<%= x["per_ch_7d"] %></td>
              <td>$<%= x["price_usd"].to_d * crypto.amount_owned %></td>
              <td>$<%= crypto.cost_per * crypto.amount_owned %></td>
              <td>$<%= (x["price_usd"].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned) %></td>
              <% @profit_los += (x["price_usd"].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned) %></td>
          <% end %>
        <% end %>
           
       
        <td>$<%= crypto.cost_per %></td>
        <td>$<%= crypto.amount_owned %></td>
       </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br/>
<br/>

<strong>Acct Profit/Loss: </strong> <%= number_to_currency(@profit_los) %>
<br/><br/>

<%= link_to 'New Crypto', new_crypto_path, class: "btn btn-info" %>

app/views/cryptos/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Crypto</h3>
  </div>
  </br>
   <div class="panel-body">


    <div class="form-group">


<%= render 'form' %>

<%= link_to 'Back', cryptos_path %>
    </div>
    </div>
</div>

app/views/cryptos/show.html.erb
<% for x in @show_crypto %>
  <% if @crypto.symbol.upcase == x["symbol"] %>
      <% crypto_name = x["name"] %>
      <% crypto_price =  x["price_usd"] %> 
      <% crypto_rank = x["rank"] %>
  <% end %>
<% end %>

<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">crypto_name</h3>
    </div>
    <div class="panel-body">
      
      <h1><%= @crypto.symbol.upcase %></h1>
    <br/><br/>

   <p>
    <strong>Current Price: </strong><%= crypto_price %>
    </p>
   
   <p>
    <strong>Rank: </strong><%= number_to_currency(crypto_rank) %>
    </p>
  
  
  <p>
    <strong>Cost per:</strong>
    <%= @crypto.cost_per %>
    </p>
    <strong>Amount owned:</strong>
    <%= @crypto.amount_owned %>
  </p>

  </div>
    <div class="panel-footer">
      <%= link_to 'Edit', edit_crypto_path(@crypto) %> |
      <%= link_to 'Delete Currency', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Back', cryptos_path %>
    </div>
  </div>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
            </button>
            <%= content_tag(:div, msg) %>
        </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Crypto App", root_path, class: "navbar-brand" %>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About Me", home_about_path %></li>
      <li><%= link_to "Lookup", home_lookup_path %></li> 
       
      
        <% if user_signed_in? %>
         <li><%= link_to "List of Cryptos", cryptos_path %></li> 
          <li><%= link_to "Add New", new_crypto_path %></li> 
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li> 
          <li><%= link_to "Edit Profile",edit_user_registration_path %></li>
        <% else %> 
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
        
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About me </h1>
<strong><u> My KIDS ARE CRAZY</u></strong>

app/views/home/index.html.erb
<h1>Welcome to Crypto Currency App</h1>

    <br/><br/>
   <table class="table table-hover table-striped table-bordered info">
     <thead>  
      <tr>
         <th>Rank</th>
         <th>Currency Type</th>
      </tr>
    </thead>
         
 
    <table class="table table-hover table-striped table-bordered info">
        <tbody> 
        
                <% @coins %>
                <% for x in @coins %>
                <% for coin in @my_coins %>
                    <% if coin == x["symbol"] %>
                    <tr>
                        <td>Rank: <%= x["rank"] %></td>
                         <td><%= x["name"] %>: $<%= x["price_usd"] %></td>
                    <% end %>
                    </tr>
             
            <% end %>
        <% end %>
        </tr>    
     </tbody>
 </table>
<br/>

app/views/home/lookup.html.erb
<h3> Look UP Crypto Currency</h3>
<br/>

<%= form_tag home_lookup_path, :method => 'POST' do %>
        <%= text_field_tag 'sym', nil, placeholder:'Enter Crypto Symbol', size: 50 %>
        <%= submit_tag 'Lookup Stock Quote' %>
    <% end %>
    
    <br/><br
    


<% if @symbol %>
    <% for x in @lookup_coin %>
    <% if @symbol == x["symbol"] %>
            <%= x["name"] %>: <% x["price_usd"] %> <br/>
            Rank: <%= x["rank"] %><br/><br/>
        <% end %>
    <% end %>
<% end %>
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CRypto Currency APP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render 'home/navbar' %>

<div class="container">
  <%= render 'home/flash' %>
  <%= yield %>
</div>
</body>
</html>